### ISSUE TITLE
ENU printing regression

### ISSUE THREAD

**Issue by garborg** [JuliaGeo/Geodesy.jl#24]
Found this a bit confusing:

```julia
julia> x_lla = LLA(-27.468937, 153.023628, 0.0)
LLA(lat=-27.468937°, lon=153.023628°, alt=0.0)

julia> x_enu = ENU(-27.468937, 153.023628, 0.0)
3-element Geodesy.ENU{Float64}:
 -27.4689
 153.024
   0.0
```

**Comment by andyferris** [comment]
Hmm this is because `ENU <: StaticVector <: Array`, since they are a Cartesian frame. I'm assuming you prefer it to print like `LLA` does?

**Comment by garborg** [comment]
I think it's fine either way -- it threw me off seeing it anew while trying to see why conversions in OpenStreetMap were segfaulting, but that makes sense to me now. Feel free to close unless you have a preference to change it.

**Comment by andyferris** [comment]
Well the `show` method was there but is being overridden due to changes in *StaticArrays* since I first wrote it, so I will restore it.
