### ISSUE TITLE
More idiomatic conversion

### ISSUE THREAD

**Issue by garborg** [JuliaGeo/Geodesy.jl#4]
`ENU(Bounds{LLA}...)` and friends aren't idiomatic because their return type is not `ENU`. Other conversions should probably be defined as conversions rather than constructors (assuming constructions that require a reference point are a fit for `convert`) so both forms work.

I tried to change this already, but it seemed more of a hassle than it's worth to support both 0.3 and 0.4 right now. Perhaps best to wait until 0.4 settles a bit (idioms will be better formed then, too).

**Comment by garborg** [comment]
See tedsteiner/OpenStreetMap.jl#61 for discussion on adding convenience methods here in Geodesy.jl for converting point types of containers like `Dict{Int,ENU}` -- for now left as a TBD until language design settles a bit.

**Comment by andyferris** [comment]
One good solution would have been to define `map` on `Bounds` to map the points in the `Bounds` container according to some function...

**Comment by andyferris** [comment]
I think this issue isn't relevant anymore? Closing
