### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by c42f** [JuliaGeo/Geodesy.jl#59]
I accidentally bumped this as part of #58, but I think we should do 1.0.0 anyway - this package is quite stable and basically works, even if development is dormant.

(Actually I'd prefer to just release 0.5.1, but since we've dropped julia-0.7 I think we technically need to release a new major version to satisfy the JuliaRegistrator bot.)

Any objections @visr? Or anyone else?

**Comment by visr** [comment]
I believe technically it needs at least a minor version bump, not pre and post 1.0. Which is only breaking pre 1.0.

But no objections to going to 1.0!

**Comment by c42f** [comment]
Oh yes. Now that you mention it, I think they might have relaxed that requirement for 0.x package versions.

Doing a quick review of the public API there's a few awkward things but the only thing which really sticks out is the `distance()` function. It seems like an overly generic name to be exporting, especially considering that some users may expect it to compute the geodetic distance.

Should rename that to `euclidean_distance`, perhaps?

**Comment by juliohm** [comment]
Not a current user of the package, but planning to use it in the future. I find it a bit strange that the transformation structs are of the form `LLAfromECEF`, `ECEFfromLLA` instead of two separate structs `LLA` and `ECEF` with a general `transform(x, LLA, ECEF)` API. Is there a reason for keeping these representations coupled? I didn't have a chance to look at the code properly, but since a discussion was started around a possible version v1.0, I thought it would be a good moment to comment on that.

Would a refactoring of the code be welcome in this sense? One in which these representations are constructed once, and individually, and then connected via a `transform` function? Producing all pairs `LLAfromECEF`, `ECEFfromLLA`, ... doesn't seem like an ideal solution from a software engineering perspective. Appreciate if you can comment on that.

**Comment by c42f** [comment]
@juliohm good question, indeed it could count as an FAQ for people who need geodetic calculations. It was definitely an intentional design choice to have mappings as fundamental rather than coordinate reference systems, and to allow these to be composed together via `∘`. First, do read https://github.com/JuliaGeo/Geodesy.jl#basic-terminology if you haven't — I put in a fair amount of work to try to explain some jargon. It could always be improved, but hopefully it's helpful.

A fundamental point is that coordinate reference systems (CRSs) are physical objects in the world (the reference frame) just as much as they are mathematical coordinatizations of space within this reference frame. Conceptually, CRSs are the objects you'd like to put into `transform` as `transform(x, crs1, crs2)`. (We don't have a CRS type, but if we did, it would likely share the same metadata model as the WKT-CRS standard.)

Because reference frames are physical objects subject to measurement error and historical accident, `transform(x, crs1, crs2)` can be performed in multiple ways depending on choices made by the user. Making the best choice is very nontrivial and can be application-dependent. The proj library has faced this challenge with a database of transformations and a method of ranking them when there's ambiguity within the database. They've recently documented their solution: https://proj.org/operations/operations_computation.html; the following quote is very telling:

> As a matter of fact with PROJ 6, there are about 60 000 lines of code dealing with “metadata” management (including conversions between PROJ strings, all CRS WKT variants), to be compared to 30 000 for the purely computation part.

In Geodesy.jl, we've sidestepped this engineering effort by only providing the mathematical transformation operators which can be used to build up geodetic transformation pipelines in an application-specific way via composition.

A secondary point is that most coordinate systems in geodesy are highly parametric. For example, LLA is parameterized by the underlying ellipsoid parameters. So your example would have to be written something like `transform(x, LLA_CS(wgs84), ECEF)`. It gets worse for UTM, which has 60 zones in north and south segments, and where the mathematical `UTMfromLLA` also depends on the underlying `LLA` ellipsoidal parameters. So we'd have `transform(x, UTM_CS(LLA_CS(wgs84)), ECEF)`, or some such. You can see that we quickly start to need a full metadata model of coordinate systems here.

Instead of all this complexity, we provide only the mathematical transformations and you can compose them in a way which suits your application.  For example, there's no predefined `UTMfromUTM` function, but it's simple to create one, for example to transform from zone 56->55 south with respect to the WGS84 ellipsoid, use `UTMfromLLA(56, false, wgs84) ∘ LLAfromUTM(55, false, wgs84)`.

> Producing all pairs LLAfromECEF, ECEFfromLLA, ... doesn't seem like an ideal solution from a software engineering perspective

Yes, but this is exactly the situation we're avoiding. A few like `UTMfromLLA` are fundamental operations which we provide, but the rest are defined by composition. We define a few commonly used compositions in this package, but the rest can be defined in user code on an as-needed basis. This transformation pipeline system is also the model used by proj (They switched to this model after many years of proj.4 which had a CRS-centric view of things, with many issues of usability and conceptual clarity. See https://proj.org/usage/transformation.html#transformation).

By the way, notice how our odd-seeming `AfromB` naming convention makes composition chains "obviously correct" because the coordinate system names are adjacent. For example, ENU from UTM could be implemented as `ENUfromECEF(...) ∘ ECEFfromLLA(...) ∘ LLAfromUTM(...)`.

**Comment by juliohm** [comment]
Thank you @c42f , I appreciate all the links and the effort to educate the community :100:

I am still not convinced why we shouldn't decouple the `LLAfromECEF` pairs. I understand that each pair has a set of parameters that needs to be carried over, but that doesn't seem to inhibit a `transform(x, FOO, BAR)` api where `FOO` and `BAR` have appropriate self-contained descriptions of the datum + crs? I will see if I can find the time to read through the links you shared. Feel free to move forward with the v1.0 idea if you feel that the `transform` idea is a step backwards.

**Comment by c42f** [comment]
> I am still not convinced why we shouldn't decouple the LLAfromECEF pairs

But in a sense, there's no decoupling possible: you need to write the mathematical function which maps LLA->ECEF somewhere.

When it comes to different datums, it becomes clearer that pairwise transformations between CRS are the fundamental building blocks on top of which other abstractions (like your desired `transform()`) can be built.

A transformation from CRS `foo` to `bar` may take many paths `foo -> baz -> bar`, `foo -> qux -> quux -> bar` etc etc through intermediate CRSs, provided that the arrows in these equations are known. But the arrows may not be known, or may be known to different accuracies. This is a fact of physical measurement: imagine placing two objects A and B on a table, then remove them without measuring their relative position. What then, was the transformation between them? You'll never know exactly, and you'll never be able to implement a precise `transform(x, A, B)`.

This example may seem absurd, but it's actually the reality in spatial measurement. Historical maps will be made relative to some survey points. But if those survey points are destroyed or moved we can no longer align things with certainty, and may never know where points in the old map fit relative to the modern world.

> but that doesn't seem to inhibit a transform(x, FOO, BAR) api where FOO and BAR have appropriate self-contained descriptions of the datum + crs

Sure, `transform(x, crs1, crs2)` is a viable and *extremely useful* high level API, and proj provides this. Internally however, they implement it in terms of a pipeline of fundamental pairwise transformations. It's actually a great idea, but it's a huge amount of work. If you want support for a wide range of `crs`, my advice is to just use proj.

**Comment by c42f** [comment]
https://github.com/JuliaRegistries/General/pull/25392
