### ISSUE TITLE
LLAfromUTMZ does not take Float64 as specified

### ISSUE THREAD

**Issue by kyle11rd** [JuliaGeo/Geodesy.jl#62]
The following code gives error:
```
julia> utmz2lla = LLAfromUTMZ(wgs84)
LLAfromUTMZ(WGS84)

julia> utmz2lla(UTMZ(562867.46, 4196685.21, 0, 10, true))
ERROR: StackOverflowError:
Stacktrace:
 [1] UTMZ(::Float64, ::Float64, ::Int64, ::UInt8, ::Bool) at C:\Users\zli3\.julia\packages\Geodesy\qjth5\src\points.jl:123 (repeats 79984 times)
```

But it works once I removed the decimal places from the easting and northing:
```
julia> utmz2lla(UTMZ(562867, 4196685, 0, 10, true))
LLA(lat=37.91553818223572°, lon=-122.28477727705008°, alt=0.0)
```

Please provide a fix to allow passing floats to LLAfromUTMZ as specified in the error message

**Comment by visr** [comment]
This call gives the X and Y as a Float64, and the Z as an Int.
```julia
UTMZ(562867.46, 4196685.21, 0, 10, true)
```

Easiest way to get around the StackOverflowError is to write `0.0` for Z: `UTMZ(562867.46, 4196685.21, 0, 10, true)`.

I submitted a fix for this issue in #64.
