### ISSUE TITLE
Transverse Mercator comment / code inconsistency

### ISSUE THREAD

**Issue by bobcassels** [JuliaGeo/Geodesy.jl#66]
Comments clearly say that the scale factor is only applied in the horizontal direction:
- https://github.com/JuliaGeo/Geodesy.jl/blob/master/src/transformations.jl#L349
- https://github.com/JuliaGeo/Geodesy.jl/blob/master/src/transformations.jl#L390

Code clearly applies the scale factor to both coordinates:
- https://github.com/JuliaGeo/Geodesy.jl/blob/master/src/transverse_mercator.jl#L644
- https://github.com/JuliaGeo/Geodesy.jl/blob/master/src/transverse_mercator.jl#L668

What is intended here? If you tell me what to change, I am happy to make the change and the appropriate PR.

**Comment by c42f** [comment]
These are three dimensional transformations.

The comments say

> scaling not applied to vertical dimension

- that is, scaling is applied in x and y, but not z ("vertical").

So I think the code is correct here.
