### ISSUE TITLE
WebMercatorfromLLA not defined

### ISSUE THREAD

**Issue by th85ac** [JuliaGeo/Geodesy.jl#77]
I am trying to use WebMercatorfromLLA... Julia tells me that is not defined. Any other transformation, function work[](url)

`ERROR: UndefVarError: WebMercatorfromLLA not defined
Stacktrace:
 [1] top-level scope
   @ ~/Documents/Hardware & Software/Julia/Geodesy/geodesy.jl:35`

**Comment by visr** [comment]
I've just tagged a release that includes this, before it was only on master.

https://github.com/JuliaGeo/Geodesy.jl/releases/tag/v1.1.0
