### ISSUE TITLE
Share Base.Graphics primitives

### ISSUE THREAD

**Issue by garborg** [JuliaGeo/Geodesy.jl#8]
This would mean looking into changes to `Base.Graphics` types and methods such that `Winston.jl` could keep using them, `Compose.jl` could start using them, and we could use them here.

**Comment by yeesian** [comment]
I've begun some work on it, in [GeoInterface.jl](https://github.com/yeesian/GeoInterface.jl/blob/master/src/GEOInterface.jl), and provided functions to convert them to Compose objects ([here](https://github.com/yeesian/GeoInterface.jl/blob/master/src/compose.jl)). Eventually these stuff should probably be under the care of [JuliaGeometry](https://github.com/JuliaGeometry)?

cc @skariel

**Comment by garborg** [comment]
@yeesian Awesome. Sounds right that eventually it should belong to JuliaGeometry if feasible.

**Comment by andyferris** [comment]
Is this issue still desired/relevant?

**Comment by yeesian** [comment]
I don't think so. We've been leaving it to the user to define their own conversion methods, with no immediate plans at anything more general.

**Comment by c42f** [comment]
Sounds good.  Personally I think Geodesy.jl should be about, well, geodesy!  As far as I can tell, geometric primitives for making maps are a rather different concern.
